apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-ebs-iops-burstbalance
    role: alert-rules
  name: sre-ebs-iops-burstbalance
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-ebs-iops-burstbalance
    rules:
    - alert: EbsVolumeBurstBalanceLowSRE
      expr: 100 - min_over_time(ebs_iops_credits[30m:5m]) > 80
      for: 60m
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeBurstBalanceEmptySRE
      expr: 100 - min_over_time(ebs_iops_credits[3h:15m]) == 100
      annotations:
        message: "The EBS volume {{ $labels.vol_id }} has exhausted its IOPs burst credit for over 2 hours"
      for: 120m
      labels:
        severity: critical
        namespace: openshift-monitoring
